% Even Fibonacci numbers
% Problem 2
% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% Project Euler
% Problem 2
% https://projecteuler.net/problem=2
% Coder: coderalhazen
clear;clc;close all;
% Problem
disp('<a href="https://projecteuler.net/problem=2">Project Euler - Problem 2</a>')
% Solution
f1 = 1;
f2 = 2;
f3 = 0;
sum = 0;
while(f3<4000000)
    f3 = f1 + f2;
    f1 = f2;
    f2 = f3;
    if(mod(f3,2)==0)
        sum = sum + f3;
    end
end
sum = sum + 2;
fprintf('The answer is: %d.\n',sum);
